
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.2.0

jobs:
  deploy-dev:
    docker:
    - image: circleci/node:12.20.2
    
    steps:
    
      - checkout
      - run:
          name: ssh
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy.sh"
          
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow 
  deploy:
    # Run the welcome/run job in its own container
    jobs:
    
      - deploy-dev:
      
        filters: 
        
          branches:
          
            only:
            
              - dev
